version: '3.8'

services:
  pollution-extraction:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../:/workspaces/dss-pollution-extraction
      - ../data:/workspaces/dss-pollution-extraction/data
      - ../output:/workspaces/dss-pollution-extraction/output
    environment:
      - PYTHONPATH=/workspaces/dss-pollution-extraction
      - PYTHONUNBUFFERED=1
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    working_dir: /workspaces/dss-pollution-extraction
